version: "3.7"

services:
  mysql: 
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symtraint
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports: 
      - "3306:3306"
    expose:
      - 3306
  symtraint:
    build: ./
    env_file: ./.env
    depends_on:
      - mysql
